In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#считываем тренировочные данные
train = pd.read_csv('train.csv')
formula_train = pd.read_csv('formula_train.csv')

print(f'train dataset shape: {train.shape}')
print(f'formula_train dataset shape: {formula_train.shape}')

train dataset shape: (17010, 82)
formula_train dataset shape: (17010, 88)

In [3]:
#считываем тестовые данные
test = pd.read_csv('test.csv')
formula_test = pd.read_csv('formula_test.csv')

print(f'test dataset shape: {test.shape}')
print(f'formula_test dataset shape: {formula_test.shape}')

test dataset shape: (4253, 81)
formula_test dataset shape: (4253, 87)

In [4]:
train.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,wtd_mean_Valence,gmean_Valence,wtd_gmean_Valence,entropy_Valence,wtd_entropy_Valence,range_Valence,wtd_range_Valence,std_Valence,wtd_std_Valence,critical_temp
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,...,2.257143,2.213364,2.219783,1.368922,1.066221,1,1.085714,0.433013,0.437059,29.0
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,...,2.257143,1.888175,2.210679,1.557113,1.047221,2,1.128571,0.632456,0.468606,26.0
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,...,2.271429,2.213364,2.232679,1.368922,1.029175,1,1.114286,0.433013,0.444697,19.0
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,...,2.264286,2.213364,2.226222,1.368922,1.048834,1,1.100000,0.433013,0.440952,22.0
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,...,2.242857,2.213364,2.206963,1.368922,1.096052,1,1.057143,0.433013,0.428809,23.0

In [5]:
formula_train.head()

,H,He,Li,Be,B,C,N,O,F,Ne,...,Au,Hg,Tl,Pb,Bi,Po,At,Rn,critical_temp,material
0,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,29.0,Ba0.2La1.8Cu1O4
1,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,26.0,Ba0.1La1.9Ag0.1Cu0.9O4
2,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,19.0,Ba0.1La1.9Cu1O4
3,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,22.0,Ba0.15La1.85Cu1O4
4,0.0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,23.0,Ba0.3La1.7Cu1O4

In [6]:
#исследуем загруженные данные (проверим на наличие пропусков)
print(train.isna().sum())
print(formula_train.isna().sum())

number_of_elements       0
mean_atomic_mass         0
wtd_mean_atomic_mass     0
gmean_atomic_mass        0
wtd_gmean_atomic_mass    0
                        ..
range_Valence            0
wtd_range_Valence        0
std_Valence              0
wtd_std_Valence          0
critical_temp            0
Length: 82, dtype: int64
H                0
He               0
Li               0
Be               0
B                0
                ..
Po               0
At               0
Rn               0
critical_temp    0
material         0
Length: 88, dtype: int64

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17010 entries, 0 to 17009
Data columns (total 82 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   number_of_elements               17010 non-null  int64
 1   mean_atomic_mass                 17010 non-null  float64
 2   wtd_mean_atomic_mass             17010 non-null  float64
 3   gmean_atomic_mass                17010 non-null  float64
 4   wtd_gmean_atomic_mass            17010 non-null  float64
 5   entropy_atomic_mass              17010 non-null  float64
 6   wtd_entropy_atomic_mass          17010 non-null  float64
 7   range_atomic_mass                17010 non-null  float64
 8   wtd_range_atomic_mass            17010 non-null  float64
 9   std_atomic_mass                  17010 non-null  float64
 10  wtd_std_atomic_mass              17010 non-null  float64
 11  mean_fie                         17010 non-null  float64
 12  wtd_mean_fie                     17010 non-null  float64
 13  gmean_fie                        17010 non-null  float64
 14  wtd_gmean_fie                    17010 non-null  float64
 15  entropy_fie                      17010 non-null  float64
 16  wtd_entropy_fie                  17010 non-null  float64
 17  range_fie                        17010 non-null  float64
 18  wtd_range_fie                    17010 non-null  float64
 19  std_fie                          17010 non-null  float64
 20  wtd_std_fie                      17010 non-null  float64
 21  mean_atomic_radius               17010 non-null  float64
 22  wtd_mean_atomic_radius           17010 non-null  float64
 23  gmean_atomic_radius              17010 non-null  float64
 24  wtd_gmean_atomic_radius          17010 non-null  float64
 25  entropy_atomic_radius            17010 non-null  float64
 26  wtd_entropy_atomic_radius        17010 non-null  float64
 27  range_atomic_radius              17010 non-null  int64
 28  wtd_range_atomic_radius          17010 non-null  float64
 29  std_atomic_radius                17010 non-null  float64
 30  wtd_std_atomic_radius            17010 non-null  float64
 31  mean_Density                     17010 non-null  float64
 32  wtd_mean_Density                 17010 non-null  float64
 33  gmean_Density                    17010 non-null  float64
 34  wtd_gmean_Density                17010 non-null  float64
 35  entropy_Density                  17010 non-null  float64
 36  wtd_entropy_Density              17010 non-null  float64
 37  range_Density                    17010 non-null  float64
 38  wtd_range_Density                17010 non-null  float64
 39  std_Density                      17010 non-null  float64
 40  wtd_std_Density                  17010 non-null  float64
 41  mean_ElectronAffinity            17010 non-null  float64
 42  wtd_mean_ElectronAffinity        17010 non-null  float64
 43  gmean_ElectronAffinity           17010 non-null  float64
 44  wtd_gmean_ElectronAffinity       17010 non-null  float64
 45  entropy_ElectronAffinity         17010 non-null  float64
 46  wtd_entropy_ElectronAffinity     17010 non-null  float64
 47  range_ElectronAffinity           17010 non-null  float64
 48  wtd_range_ElectronAffinity       17010 non-null  float64
 49  std_ElectronAffinity             17010 non-null  float64
 50  wtd_std_ElectronAffinity         17010 non-null  float64
 51  mean_FusionHeat                  17010 non-null  float64
 52  wtd_mean_FusionHeat              17010 non-null  float64
 53  gmean_FusionHeat                 17010 non-null  float64
 54  wtd_gmean_FusionHeat             17010 non-null  float64
 55  entropy_FusionHeat               17010 non-null  float64
 56  wtd_entropy_FusionHeat           17010 non-null  float64
 57  range_FusionHeat                 17010 non-null  float64
 58  wtd_range_FusionHeat             17010 non-null  float64
 59  std_FusionHeat                   17010 non-null  float64
 60  wtd_std_FusionHeat               17010 non-null  float64
 61  mean_ThermalConductivity         17010 non-null  float64
 62  wtd_mean_ThermalConductivity     17010 non-null  float64
 63  gmean_ThermalConductivity        17010 non-null  float64
 64  wtd_gmean_ThermalConductivity    17010 non-null  float64
 65  entropy_ThermalConductivity      17010 non-null  float64
 66  wtd_entropy_ThermalConductivity  17010 non-null  float64
 67  range_ThermalConductivity        17010 non-null  float64
 68  wtd_range_ThermalConductivity    17010 non-null  float64
 69  std_ThermalConductivity          17010 non-null  float64
 70  wtd_std_ThermalConductivity      17010 non-null  float64
 71  mean_Valence                     17010 non-null  float64
 72  wtd_mean_Valence                 17010 non-null  float64
 73  gmean_Valence                    17010 non-null  float64
 74  wtd_gmean_Valence                17010 non-null  float64
 75  entropy_Valence                  17010 non-null  float64
 76  wtd_entropy_Valence              17010 non-null  float64
 77  range_Valence                    17010 non-null  int64
 78  wtd_range_Valence                17010 non-null  float64
 79  std_Valence                      17010 non-null  float64
 80  wtd_std_Valence                  17010 non-null  float64
 81  critical_temp                    17010 non-null  float64
dtypes: float64(79), int64(3)
memory usage: 10.6 MB

In [8]:
formula_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17010 entries, 0 to 17009
Data columns (total 88 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   H              17010 non-null  float64
 1   He             17010 non-null  int64
 2   Li             17010 non-null  float64
 3   Be             17010 non-null  float64
 4   B              17010 non-null  float64
 5   C              17010 non-null  float64
 6   N              17010 non-null  float64
 7   O              17010 non-null  float64
 8   F              17010 non-null  float64
 9   Ne             17010 non-null  int64
 10  Na             17010 non-null  float64
 11  Mg             17010 non-null  float64
 12  Al             17010 non-null  float64
 13  Si             17010 non-null  float64
 14  P              17010 non-null  float64
 15  S              17010 non-null  float64
 16  Cl             17010 non-null  float64
 17  Ar             17010 non-null  int64
 18  K              17010 non-null  float64
 19  Ca             17010 non-null  float64
 20  Sc             17010 non-null  float64
 21  Ti             17010 non-null  float64
 22  V              17010 non-null  float64
 23  Cr             17010 non-null  float64
 24  Mn             17010 non-null  float64
 25  Fe             17010 non-null  float64
 26  Co             17010 non-null  float64
 27  Ni             17010 non-null  float64
 28  Cu             17010 non-null  float64
 29  Zn             17010 non-null  float64
 30  Ga             17010 non-null  float64
 31  Ge             17010 non-null  float64
 32  As             17010 non-null  float64
 33  Se             17010 non-null  float64
 34  Br             17010 non-null  float64
 35  Kr             17010 non-null  int64
 36  Rb             17010 non-null  float64
 37  Sr             17010 non-null  float64
 38  Y              17010 non-null  float64
 39  Zr             17010 non-null  float64
 40  Nb             17010 non-null  float64
 41  Mo             17010 non-null  float64
 42  Tc             17010 non-null  float64
 43  Ru             17010 non-null  float64
 44  Rh             17010 non-null  float64
 45  Pd             17010 non-null  float64
 46  Ag             17010 non-null  float64
 47  Cd             17010 non-null  float64
 48  In             17010 non-null  float64
 49  Sn             17010 non-null  float64
 50  Sb             17010 non-null  float64
 51  Te             17010 non-null  float64
 52  I              17010 non-null  float64
 53  Xe             17010 non-null  int64
 54  Cs             17010 non-null  float64
 55  Ba             17010 non-null  float64
 56  La             17010 non-null  float64
 57  Ce             17010 non-null  float64
 58  Pr             17010 non-null  float64
 59  Nd             17010 non-null  float64
 60  Pm             17010 non-null  int64
 61  Sm             17010 non-null  float64
 62  Eu             17010 non-null  float64
 63  Gd             17010 non-null  float64
 64  Tb             17010 non-null  float64
 65  Dy             17010 non-null  float64
 66  Ho             17010 non-null  float64
 67  Er             17010 non-null  float64
 68  Tm             17010 non-null  float64
 69  Yb             17010 non-null  float64
 70  Lu             17010 non-null  float64
 71  Hf             17010 non-null  float64
 72  Ta             17010 non-null  float64
 73  W              17010 non-null  float64
 74  Re             17010 non-null  float64
 75  Os             17010 non-null  float64
 76  Ir             17010 non-null  float64
 77  Pt             17010 non-null  float64
 78  Au             17010 non-null  float64
 79  Hg             17010 non-null  float64
 80  Tl             17010 non-null  float64
 81  Pb             17010 non-null  float64
 82  Bi             17010 non-null  float64
 83  Po             17010 non-null  int64
 84  At             17010 non-null  int64
 85  Rn             17010 non-null  int64
 86  critical_temp  17010 non-null  float64
 87  material       17010 non-null  object
dtypes: float64(78), int64(9), object(1)
memory usage: 11.4+ MB

In [9]:
print(test.isna().sum())
print(formula_test.isna().sum())

number_of_elements       0
mean_atomic_mass         0
wtd_mean_atomic_mass     0
gmean_atomic_mass        0
wtd_gmean_atomic_mass    0
                        ..
wtd_entropy_Valence      0
range_Valence            0
wtd_range_Valence        0
std_Valence              0
wtd_std_Valence          0
Length: 81, dtype: int64
H           0
He          0
Li          0
Be          0
B           0
           ..
Bi          0
Po          0
At          0
Rn          0
material    0
Length: 87, dtype: int64

In [10]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4253 entries, 0 to 4252
Data columns (total 81 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   number_of_elements               4253 non-null   int64
 1   mean_atomic_mass                 4253 non-null   float64
 2   wtd_mean_atomic_mass             4253 non-null   float64
 3   gmean_atomic_mass                4253 non-null   float64
 4   wtd_gmean_atomic_mass            4253 non-null   float64
 5   entropy_atomic_mass              4253 non-null   float64
 6   wtd_entropy_atomic_mass          4253 non-null   float64
 7   range_atomic_mass                4253 non-null   float64
 8   wtd_range_atomic_mass            4253 non-null   float64
 9   std_atomic_mass                  4253 non-null   float64
 10  wtd_std_atomic_mass              4253 non-null   float64
 11  mean_fie                         4253 non-null   float64
 12  wtd_mean_fie                     4253 non-null   float64
 13  gmean_fie                        4253 non-null   float64
 14  wtd_gmean_fie                    4253 non-null   float64
 15  entropy_fie                      4253 non-null   float64
 16  wtd_entropy_fie                  4253 non-null   float64
 17  range_fie                        4253 non-null   float64
 18  wtd_range_fie                    4253 non-null   float64
 19  std_fie                          4253 non-null   float64
 20  wtd_std_fie                      4253 non-null   float64
 21  mean_atomic_radius               4253 non-null   float64
 22  wtd_mean_atomic_radius           4253 non-null   float64
 23  gmean_atomic_radius              4253 non-null   float64
 24  wtd_gmean_atomic_radius          4253 non-null   float64
 25  entropy_atomic_radius            4253 non-null   float64
 26  wtd_entropy_atomic_radius        4253 non-null   float64
 27  range_atomic_radius              4253 non-null   int64
 28  wtd_range_atomic_radius          4253 non-null   float64
 29  std_atomic_radius                4253 non-null   float64
 30  wtd_std_atomic_radius            4253 non-null   float64
 31  mean_Density                     4253 non-null   float64
 32  wtd_mean_Density                 4253 non-null   float64
 33  gmean_Density                    4253 non-null   float64
 34  wtd_gmean_Density                4253 non-null   float64
 35  entropy_Density                  4253 non-null   float64
 36  wtd_entropy_Density              4253 non-null   float64
 37  range_Density                    4253 non-null   float64
 38  wtd_range_Density                4253 non-null   float64
 39  std_Density                      4253 non-null   float64
 40  wtd_std_Density                  4253 non-null   float64
 41  mean_ElectronAffinity            4253 non-null   float64
 42  wtd_mean_ElectronAffinity        4253 non-null   float64
 43  gmean_ElectronAffinity           4253 non-null   float64
 44  wtd_gmean_ElectronAffinity       4253 non-null   float64
 45  entropy_ElectronAffinity         4253 non-null   float64
 46  wtd_entropy_ElectronAffinity     4253 non-null   float64
 47  range_ElectronAffinity           4253 non-null   float64
 48  wtd_range_ElectronAffinity       4253 non-null   float64
 49  std_ElectronAffinity             4253 non-null   float64
 50  wtd_std_ElectronAffinity         4253 non-null   float64
 51  mean_FusionHeat                  4253 non-null   float64
 52  wtd_mean_FusionHeat              4253 non-null   float64
 53  gmean_FusionHeat                 4253 non-null   float64
 54  wtd_gmean_FusionHeat             4253 non-null   float64
 55  entropy_FusionHeat               4253 non-null   float64
 56  wtd_entropy_FusionHeat           4253 non-null   float64
 57  range_FusionHeat                 4253 non-null   float64
 58  wtd_range_FusionHeat             4253 non-null   float64
 59  std_FusionHeat                   4253 non-null   float64
 60  wtd_std_FusionHeat               4253 non-null   float64
 61  mean_ThermalConductivity         4253 non-null   float64
 62  wtd_mean_ThermalConductivity     4253 non-null   float64
 63  gmean_ThermalConductivity        4253 non-null   float64
 64  wtd_gmean_ThermalConductivity    4253 non-null   float64
 65  entropy_ThermalConductivity      4253 non-null   float64
 66  wtd_entropy_ThermalConductivity  4253 non-null   float64
 67  range_ThermalConductivity        4253 non-null   float64
 68  wtd_range_ThermalConductivity    4253 non-null   float64
 69  std_ThermalConductivity          4253 non-null   float64
 70  wtd_std_ThermalConductivity      4253 non-null   float64
 71  mean_Valence                     4253 non-null   float64
 72  wtd_mean_Valence                 4253 non-null   float64
 73  gmean_Valence                    4253 non-null   float64
 74  wtd_gmean_Valence                4253 non-null   float64
 75  entropy_Valence                  4253 non-null   float64
 76  wtd_entropy_Valence              4253 non-null   float64
 77  range_Valence                    4253 non-null   int64
 78  wtd_range_Valence                4253 non-null   float64
 79  std_Valence                      4253 non-null   float64
 80  wtd_std_Valence                  4253 non-null   float64
dtypes: float64(78), int64(3)
memory usage: 2.6 MB

In [11]:
formula_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4253 entries, 0 to 4252
Data columns (total 87 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   H         4253 non-null   float64
 1   He        4253 non-null   int64
 2   Li        4253 non-null   float64
 3   Be        4253 non-null   float64
 4   B         4253 non-null   float64
 5   C         4253 non-null   float64
 6   N         4253 non-null   float64
 7   O         4253 non-null   float64
 8   F         4253 non-null   float64
 9   Ne        4253 non-null   int64
 10  Na        4253 non-null   float64
 11  Mg        4253 non-null   float64
 12  Al        4253 non-null   float64
 13  Si        4253 non-null   float64
 14  P         4253 non-null   float64
 15  S         4253 non-null   float64
 16  Cl        4253 non-null   float64
 17  Ar        4253 non-null   int64
 18  K         4253 non-null   float64
 19  Ca        4253 non-null   float64
 20  Sc        4253 non-null   float64
 21  Ti        4253 non-null   float64
 22  V         4253 non-null   float64
 23  Cr        4253 non-null   float64
 24  Mn        4253 non-null   float64
 25  Fe        4253 non-null   float64
 26  Co        4253 non-null   float64
 27  Ni        4253 non-null   float64
 28  Cu        4253 non-null   float64
 29  Zn        4253 non-null   float64
 30  Ga        4253 non-null   float64
 31  Ge        4253 non-null   float64
 32  As        4253 non-null   float64
 33  Se        4253 non-null   float64
 34  Br        4253 non-null   float64
 35  Kr        4253 non-null   int64
 36  Rb        4253 non-null   float64
 37  Sr        4253 non-null   float64
 38  Y         4253 non-null   float64
 39  Zr        4253 non-null   float64
 40  Nb        4253 non-null   float64
 41  Mo        4253 non-null   float64
 42  Tc        4253 non-null   float64
 43  Ru        4253 non-null   float64
 44  Rh        4253 non-null   float64
 45  Pd        4253 non-null   float64
 46  Ag        4253 non-null   float64
 47  Cd        4253 non-null   float64
 48  In        4253 non-null   float64
 49  Sn        4253 non-null   float64
 50  Sb        4253 non-null   float64
 51  Te        4253 non-null   float64
 52  I         4253 non-null   float64
 53  Xe        4253 non-null   int64
 54  Cs        4253 non-null   float64
 55  Ba        4253 non-null   float64
 56  La        4253 non-null   float64
 57  Ce        4253 non-null   float64
 58  Pr        4253 non-null   float64
 59  Nd        4253 non-null   float64
 60  Pm        4253 non-null   int64
 61  Sm        4253 non-null   float64
 62  Eu        4253 non-null   float64
 63  Gd        4253 non-null   float64
 64  Tb        4253 non-null   float64
 65  Dy        4253 non-null   float64
 66  Ho        4253 non-null   float64
 67  Er        4253 non-null   float64
 68  Tm        4253 non-null   float64
 69  Yb        4253 non-null   float64
 70  Lu        4253 non-null   float64
 71  Hf        4253 non-null   float64
 72  Ta        4253 non-null   float64
 73  W         4253 non-null   float64
 74  Re        4253 non-null   float64
 75  Os        4253 non-null   float64
 76  Ir        4253 non-null   float64
 77  Pt        4253 non-null   float64
 78  Au        4253 non-null   float64
 79  Hg        4253 non-null   float64
 80  Tl        4253 non-null   float64
 81  Pb        4253 non-null   float64
 82  Bi        4253 non-null   float64
 83  Po        4253 non-null   int64
 84  At        4253 non-null   int64
 85  Rn        4253 non-null   int64
 86  material  4253 non-null   object
dtypes: float64(77), int64(9), object(1)
memory usage: 2.8+ MB

In [12]:
#объединяю train и formula_train для удобства дальнейшей работы
formula_train = formula_train.drop(columns=['critical_temp'])
train_full = pd.concat([train, formula_train], axis=1)
print(train_full.shape)

(17010, 169)

In [13]:
#из анализа данных понятно, что для дальнейше работы нам не понадобится признак "material"
train_full.drop(columns = ['material'], inplace=True)

In [14]:
train_full.head()

,number_of_elements,mean_atomic_mass,wtd_mean_atomic_mass,gmean_atomic_mass,wtd_gmean_atomic_mass,entropy_atomic_mass,wtd_entropy_atomic_mass,range_atomic_mass,wtd_range_atomic_mass,std_atomic_mass,...,Ir,Pt,Au,Hg,Tl,Pb,Bi,Po,At,Rn
0,4,88.944468,57.862692,66.361592,36.116612,1.181795,1.062396,122.90607,31.794921,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
1,5,92.729214,58.518416,73.132787,36.396602,1.449309,1.057755,122.90607,36.161939,47.094633,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
2,4,88.944468,57.885242,66.361592,36.122509,1.181795,0.975980,122.90607,35.741099,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
3,4,88.944468,57.873967,66.361592,36.119560,1.181795,1.022291,122.90607,33.768010,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0
4,4,88.944468,57.840143,66.361592,36.110716,1.181795,1.129224,122.90607,27.848743,51.968828,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0

In [15]:
#определим вектор признаков и вектор ответов
X = train_full.drop(columns=['critical_temp'])
y = train_full['critical_temp']

print(X.shape)
print(y.shape)

(17010, 167)
(17010,)

In [16]:
#производим теже самые действия по обработке данных над тестовым набором данных
test_full = pd.concat([test, formula_test], axis=1)
print(test_full.shape)

(4253, 168)

In [17]:
test_full.drop(columns = ['material'], inplace=True)
print(test_full.shape)

(4253, 167)

In [18]:
#разделяю на тренировочную и тестовую подвыборки датасет train
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(11907, 167) (11907,)
(5103, 167) (5103,)

In [19]:
!pip install sklearn

Requirement already satisfied: sklearn in c:\users\ivan\anaconda3\lib\site-packages (0.0.post1)

In [20]:
#обучаю модель, использую метрики: средняя абсолютная ошибка, средняя квадратичная ошибка и коэффициент детерминации
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [21]:
#создадим модель линейной регрессии
model = LinearRegression()

#обучим модель на тренировочном наборе данных
model.fit(X_train, y_train)

LinearRegression()

In [22]:
print(model.coef_)
print(model.intercept_)

[ 1.70854267e+00  9.22704860e-01 -1.29158945e+00 -4.73289062e-01
  7.74948790e-01 -2.20388691e+01  1.99189024e+00  2.15792062e-01
  1.17985708e-01 -5.81392144e-01  6.36077214e-02 -2.57792031e-01
  1.02396330e-01  2.17929591e-01 -4.80725372e-02 -5.22618927e+00
  5.78119227e+01  4.57550914e-02  1.52962919e-02 -6.89916294e-02
 -4.68844227e-02 -5.10209268e-01  1.74026873e+00  2.42043053e-01
 -1.46603564e+00 -3.65620389e+01  2.11392595e+01  2.86492210e-02
 -6.38127798e-02 -2.59615739e-01  1.35237792e-02 -5.28524350e-03
  4.92236478e-03  6.63378811e-04 -5.35693988e-04 -4.08177120e+00
 -1.92480597e+00 -1.07920942e-03 -7.51264783e-04  3.78931993e-03
 -1.31716570e-03 -1.24601543e-02  3.58412558e-01  8.61527808e-02
 -4.35708852e-01  1.09690611e+01 -1.96317258e+01 -3.31344317e-01
 -7.74343894e-02  1.13493344e+00 -4.77079925e-01  1.34593140e+00
 -1.93583885e+00 -8.83748525e-01  1.36962271e+00 -2.18012406e+01
  2.28842953e+01 -9.38555727e-02  6.77567245e-01 -1.26027912e+00
  9.30668227e-01 -9.20590851e-02  5.16741856e-01 -4.10937672e-02
 -3.49247004e-01  1.50942787e+01  1.07647468e+00 -1.12928873e-01
 -1.99475832e-01  3.68320986e-01 -7.34978798e-03  3.60245595e+00
 -9.26853998e+00  7.05904611e-01  5.87219680e+00  6.03288845e+01
 -7.21477678e+01  4.49591413e+00 -1.93358837e+00  2.09582626e+00
 -1.78939326e+01 -6.19550761e-01  2.06998862e-11  3.13402941e+00
 -1.90786002e-01 -2.80823613e-01 -1.94299751e-01  6.00118280e-01
 -3.16406601e-01  7.85852659e+00 -6.14441831e-12  8.31526654e+00
  4.60684065e-01 -5.41994449e-02 -1.57438582e+00 -1.64461038e+00
 -2.10719966e+00 -7.55052778e+00 -8.30358005e-12  1.22463494e+01
  1.66758332e+00  7.52924428e-01 -6.78455782e-02  5.70484622e-02
 -3.43795143e-01  1.84388829e-01  1.07674815e+00 -1.13035541e+00
 -2.90063309e-01 -6.39632387e-01 -5.16747679e-02  3.48683420e-01
 -1.20645692e+00 -1.89604111e+00 -1.00023035e+00 -2.37805192e+00
 -1.65201186e-12  1.28361161e+01 -5.99193215e-01 -3.07243926e-01
  5.01715878e-03  1.06017683e-01  1.15135269e-01  2.13741011e+00
  3.10504716e-01 -2.51565826e-01  5.82829166e-02 -1.16001849e+01
 -1.59122436e-01  9.08200645e-01 -3.78159839e-02 -1.74860652e-01
  6.32036644e-02  6.29364015e+00 -4.84945417e-13  9.11776711e+00
  8.71005391e+00  2.39092861e-02 -1.07707845e+00  7.54923277e-03
 -1.74519009e+00 -3.67705866e-13  1.00243777e+00 -1.16254778e+00
 -2.02812475e-01 -3.93425495e-01  3.46929334e+00  2.91473473e+00
  1.86119437e+00 -1.63925561e-02  3.03430722e+00  4.04851472e+00
 -1.87656464e+00  1.81904117e-01  6.87456740e-01 -9.80184751e-02
  1.16068308e+00 -6.69118849e-02  4.26540537e+00 -5.58994819e-01
  7.42286139e+00  4.86902238e+00  1.10243360e+00  6.19025310e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00]
-3.1383899570482754

In [23]:
featurs = test_full.columns

In [24]:
coeff_df = pd.DataFrame(model.coef_, columns=['Coeff'])
coeff_df['featurs'] = featurs

In [25]:
coeff_df.sort_values(by='Coeff')

        Coeff                       featurs
76 -72.147768           wtd_entropy_Valence
25 -36.562039         entropy_atomic_radius
5  -22.038869           entropy_atomic_mass
55 -21.801241            entropy_FusionHeat
46 -19.631726  wtd_entropy_ElectronAffinity
..        ...                           ...
65  15.094279   entropy_ThermalConductivity
26  21.139259     wtd_entropy_atomic_radius
56  22.884295        wtd_entropy_FusionHeat
16  57.811923               wtd_entropy_fie
75  60.328884               entropy_Valence

[167 rows x 2 columns]

In [26]:
#предскажем результат для тех же самых тренировочных данных
y_pred = model.predict(X_test)

print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

12.68778520295374
290.886499220787
0.7541519622365278

In [35]:
#реализуем кросс-валидацию
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

num_folds = 5
seed = 7

kfold = KFold(n_splits=num_folds, random_state=seed, shuffle = True)

model2 = LinearRegression()
model2.fit(X_train, y_train)
scores = cross_val_score(model2, X, y, cv=kfold, scoring='r2')

print(scores)
print(scores.mean())

[ 0.76383793  0.19156208 -0.49669365  0.74962019  0.77696281]
0.3970578738410386

In [36]:
#формируем файл с ответом для kaggle
y_pred_test = model2.predict(test_full)

In [28]:
y_pred_test = pd.DataFrame(y_pred_test, columns=['critical_temp'])
y_pred_test = y_pred_test.reset_index()

y_pred_test.to_csv('solution.csv', index=False)